 all: GradeS.cpp
	g++ GradeS.cpp  -g -Wall -std=c++11 -o grades -O2 -L /opt/OpenBLAS/lib -DARMA_DONT_USE_WRAPPER -L /home/amartya/sparse-recovery/libs/SuperLU_4.3/lib -I /opt/OpenBLAS/include -lopenblas -llapack -larpack -lsuperlu_4.3 -I /home/amartya/sparse-recovery/libs/armadillo-6.100.1/include 

